inputs:
- branch: master
  path: ".tekton/ci"
  type: git
  service: ${tekton-pipeline-repo}
- branch: master
  path: git
  type: git
  service: ${tekton-task-repo}
- branch: master
  path: container-registry
  type: git
  service: ${tekton-task-repo}
- branch: master
  path: kubernetes-service
  type: git
  service: ${tekton-task-repo}
properties:
- name: apikey
  type: SECURE
  value: ${api-key}
- name: app-name
  type: TEXT
  value: ${app-name}
- name: cluster-name
  type: TEXT
  value: mycluster
- name: branch
  type: TEXT
  value: ${git-branch}
- name: image-name
  type: TEXT
  value: ${image-name}
- name: repository
  type: TEXT
  value: "" # will be inferred from toolchain introspection
- name: registry-domain
  type: TEXT
  value: us.cr.io # ${REGISTRY_REGION_ID}
- name: registry-namespace
  type: TEXT
  value: ${registry-namespace}
- name: policy-name
  type: TEXT
  value: ${policy-name}
- name: umbrella-repo-name
  type: TEXT
  value: ${umbrella-repo-name}
triggers:
- eventListener: event-listener-manual-run
  name: Manual Trigger
  type: manual
- branch: master
  eventListener: event-listener-git-commit
  events:
    push: true
  name: Git Trigger
  type: git
  service: ${source-repo}
