apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: record-build-task
spec:
  params:
    - name: app-name
      description: Logical application name for DevOps Insights
    - name: toolchain-id
      description: Toolchain service instance id
    - name: build-number
      description: Pipeline build number
    - name: repository
      description: Repository url 
    - name: branch
      description: Repository branch
    - name: commit-id
      description: Repository commit id
    - name: continuous-delivery-context-secret
      description: name of the configmap containing the continuous delivery pipeline context secrets
      default: cd-secret
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
  workspaces:
    - name: artifacts
      description: the artifacts folder for this task
      mountPath: /artifacts
  steps:
    - name: publish-build-record
      image: ibmcom/pipeline-base-image
      workingDir: /artifacts
      env:
        - name: APP_NAME
          value: $(inputs.params.app-name)
        - name: TOOLCHAIN_ID
          value: $(inputs.params.toolchain-id)  
        - name: BUILD_NUMBER
          value: $(inputs.params.build-number)
        - name: GIT_URL
          value: $(inputs.params.repository) 
        - name: GIT_BRANCH
          value: $(inputs.params.branch)   
        - name: GIT_COMMIT
          value: $(inputs.params.commit-id)
        - name: IBM_CLOUD_API
          value: $(inputs.params.ibmcloud-api)   
        - name: IBM_CLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              name: $(inputs.params.continuous-delivery-context-secret)
              key: API_KEY
              optional: true
      script: |
          #!/bin/bash
          set -x
          set -e -o pipefail
          ##########################################################################
          # Setting HOME explicitly to have ibmcloud plugins available
          # doing the export rather than env definition is a workaround
          # until https://github.com/tektoncd/pipeline/issues/1836 is fixed
          export HOME="/root"
          ##########################################################################
          echo "APP_NAME='${APP_NAME}'" >> ./build.properties
          cat ./build.properties | grep -v -i password
          BUILD_STATUS=pass
          
          if [[ "$IBM_CLOUD_API" == *test* ]]; then
            export IBM_CLOUD_DEVOPS_ENV=dev
          fi
          export TOOLCHAIN_ID=${TOOLCHAIN_ID} # for doi plugin
          ibmcloud login --apikey ${IBM_CLOUD_API_KEY} -a ${IBM_CLOUD_API} --no-region
          ibmcloud doi publishbuildrecord --logicalappname="${APP_NAME}" --buildnumber=${BUILD_NUMBER} --branch=${GIT_BRANCH} --repositoryurl=${GIT_URL} --commitid=${GIT_COMMIT} --status=${BUILD_STATUS}
      volumeMounts:
        - mountPath: /cd-config
          name: cd-config-volume
  volumes:
    - name: cd-config-volume
      configMap:
        name: toolchain
        items:
          - key: toolchain.json
            path: toolchain.json